name: Update Cache

on:
  push:
    branches: ["main"]
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: x86_64-unknown-linux-gnu-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            x86_64-unknown-linux-gnu-

      - name: Run format check
        run: cargo fmt --check

      - name: Run linter and tests (default)
        env:
          WORTERBUCH_LICENSE_PUBLIC_KEY: ${{ secrets.WORTERBUCH_TEST_LICENSE_PUBLIC_KEY }}
        run: |
          cargo clippy -- --deny warnings &&
            cargo test

      - name: Run linter and tests (embedded)
        env:
          WORTERBUCH_LICENSE_PUBLIC_KEY: ${{ secrets.WORTERBUCH_TEST_LICENSE_PUBLIC_KEY }}
        run: |
          cargo clippy --no-default-features -- --deny warnings &&
            cargo test --no-default-features

      - name: Run linter and tests (commercial)
        env:
          WORTERBUCH_LICENSE_PUBLIC_KEY: ${{ secrets.WORTERBUCH_TEST_LICENSE_PUBLIC_KEY }}
          WORTERBUCH_LICENSE_FILE: ./test/license
        run: |
          cargo clippy --features=commercial -- --deny warnings &&
            cargo test --features=commercial

      - name: Run linter and tests (embedded commercial)
        env:
          WORTERBUCH_LICENSE_PUBLIC_KEY: ${{ secrets.WORTERBUCH_TEST_LICENSE_PUBLIC_KEY }}
          WORTERBUCH_LICENSE_FILE: ./test/license
        run: |
          cargo clippy --no-default-features --features=commercial -- --deny warnings &&
            cargo test --no-default-features --features=commercial

  release-dryrun:
    needs: test
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-24.04
            ext: ""
            args: ""
            label: ""
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-24.04
            ext: ""
            args: "--no-default-features"
            label: "embedded-"
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-24.04
            ext: ""
            args: "--features=commercial"
            label: "commercial-"
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-24.04
            ext: ""
            args: "--no-default-features --features=commercial"
            label: "embedded-commercial-"
          - target: aarch64-unknown-linux-gnu
            image: ubuntu-24.04-arm
            ext: ""
            args: "--no-default-features"
            label: ""
          - target: arm-unknown-linux-gnueabihf
            image: ubuntu-24.04-arm
            ext: ""
            args: "--no-default-features"
            label: ""
          - target: armv7-unknown-linux-gnueabihf
            image: ubuntu-24.04-arm
            ext: ""
            args: "--no-default-features"
            label: ""
          - target: x86_64-pc-windows-msvc
            image: windows-2022
            ext: ".exe"
            args: "--no-default-features"
            label: ""
          - target: aarch64-apple-darwin
            image: macos-15
            ext: ""
            args: "--no-default-features"
            label: ""
          - target: x86_64-apple-darwin
            image: macos-15-intel
            ext: ""
            args: "--no-default-features"
            label: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.label }}${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.label }}${{ matrix.target }}-

      - name: Build
        env:
          WORTERBUCH_LICENSE_PUBLIC_KEY: ${{ secrets.WORTERBUCH_LICENSE_PUBLIC_KEY }}
        run: cargo build --release ${{ matrix.args }}
